version: "3.8"
services:
  proxy-nginx:
    image: nginx
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - "3050:80"

  backend:
    build:
      context: ./RecruitmentSystem
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: "http://+:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
